### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by RyukSenpai** [OpenTabletDriver/TabletDriverFilters#20] opened 2021-11-02 05:12 UTC
# Support Request
 My tablet driver smoothing isn't working
 I am using the devocub filters in my OTD and it isn't how it normally feels its very choppy and feels like 30 fps

## What I've already tried
 just reinstalling but not any help

**Comment by xmopi** [comment] 2021-11-29 01:24
The fixes from this commit upstream need to be implemented here for this to be fixed
[f28f3928a289d7fe9ae3641dc637ec69151fd89a](https://github.com/Devocub/TabletDriver/commit/f28f3928a289d7fe9ae3641dc637ec69151fd89a)

**Comment by X9VoiD** [comment] 2021-11-29 10:59
We already have this "fix" even before Devocub commited those changes upstream.

https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Desktop/Interop/Timer/LinuxTimer.cs

**Comment by X9VoiD** [comment] 2021-11-29 11:01
Closing this issue since this is not reproducible on our side.

**Closed as completed by X9VoiD** 2021-11-29 11:01 UTC
